(() => {
  const subjects = ['Math', 'English', 'Science', 'History', 'General'];
  const root = document.getElementById('root'); if (!root) return;
  root.innerHTML = `<div class="ai-tutor-float" aria-hidden="true"><div class="ai-tutor-mascot"><div class="ai-tutor-eyes"><div class="ai-tutor-eye"><span></span></div><div class="ai-tutor-eye"><span></span></div></div></div><span class="ai-tutor-label">AI Tutor</span></div><div class="landing"><header class="landing-header"><a href="/" class="landing-logo"><span class="logo-icon">✦</span><span class="logo-text">AITutor</span></a><a href="/chats.html" class="header-chats-link">💬 My Chats</a></header><section class="landing-hero"><h1>Your AI Homework Helper</h1><p class="landing-subtitle">Snap a photo or type your question. Get clear, step-by-step answers in seconds.</p></section><div class="subject-chips stagger-in">${subjects.map((s) => `<button class="chip" data-subject="${s}">${s}</button>`).join('')}</div><form class="input-card" id="landing-form"><div class="input-card-inner"><div class="image-preview-bar" hidden><img class="image-thumb" alt="Uploaded"><span class="image-name"></span><button type="button" class="image-remove">✕</button></div><div class="input-card-calc" hidden></div><textarea class="input-textarea" rows="3" placeholder="Ask anything... e.g. Solve for x: 2x + 5 = 15"></textarea><div class="input-actions"><div class="input-tools"><input id="homework-image" type="file" accept="image/*" capture="environment" hidden><button type="button" class="tool-btn camera-btn">⌾</button><button type="button" class="tool-btn calc-toggle">⌗</button></div><button type="submit" class="send-btn">Solve <span class="btn-arrow">→</span></button></div></div><p class="input-error" hidden></p></form><section class="features stagger-in"><div class="feature hover-3d"><div class="feature-icon-wrap">◉</div><h3>Camera Input</h3><p>Snap a photo of any homework problem and get instant help.</p></div><div class="feature hover-3d"><div class="feature-icon-wrap">⌗</div><h3>Calculator ×2</h3><p>Scientific calculator and unit conversion tools for everyday study.</p></div><div class="feature hover-3d"><div class="feature-icon-wrap">✦</div><h3>All Subjects</h3><p>Math, English, Science, History, and General topics in one tutor.</p></div></section><section class="partnerships stagger-in"><div class="partnerships-heading"><div><p class="partnerships-kicker"><span class="kicker-dot"></span> The learning ecosystem</p><h2>Better together.</h2><p class="partnerships-intro">AITutor connects explanations, practice, and progress in one calm place.</p></div><div class="partnerships-orbit">✦</div></div></section><footer class="landing-footer">AITutor — Learn anything, faster.</footer></div>`;
  let subject = 'General'; let image = '';
  const textarea = root.querySelector('.input-textarea'); const error = root.querySelector('.input-error'); const preview = root.querySelector('.image-preview-bar'); const file = root.querySelector('#homework-image');
  root.querySelectorAll('[data-subject]').forEach((button) => button.addEventListener('click', () => { subject = button.dataset.subject; root.querySelectorAll('[data-subject]').forEach((item) => item.classList.toggle('active', item === button)); textarea.focus(); }));
  root.querySelector('.camera-btn').addEventListener('click', () => file.click());
  file.addEventListener('change', () => { const selected = file.files && file.files[0]; if (!selected) return; if (!selected.type.startsWith('image/') || selected.size > 5 * 1024 * 1024) { error.textContent = 'Choose an image smaller than 5 MB.'; error.hidden = false; return; } const reader = new FileReader(); reader.onload = () => { image = String(reader.result); preview.querySelector('img').src = image; preview.querySelector('.image-name').textContent = selected.name; preview.hidden = false; }; reader.readAsDataURL(selected); });
  preview.querySelector('button').addEventListener('click', () => { image = ''; preview.hidden = true; });
  root.querySelector('.calc-toggle').addEventListener('click', () => { const box = root.querySelector('.input-card-calc'); box.hidden = !box.hidden; if (!box.hidden) { box.innerHTML = '<div class="mini-calculator"><input class="mini-calc-input" placeholder="2 + 2 * 3"><button type="button" class="mini-calc-run">Calculate</button><output class="mini-calc-result"></output></div>'; box.querySelector('button').addEventListener('click', () => { const value = box.querySelector('input').value; try { if (!/^[0-9+*/().%\s-]+$/.test(value)) throw new Error('Numbers and operators only'); box.querySelector('output').textContent = String(Function(`return (${value})`)()); } catch { box.querySelector('output').textContent = 'Invalid expression'; } }); } });
  root.querySelector('#landing-form').addEventListener('submit', (event) => { event.preventDefault(); if (!textarea.value.trim() && !image) { error.textContent = 'Type a question or add a photo.'; error.hidden = false; return; } sessionStorage.setItem('ai-tutor-pending', JSON.stringify({ prompt: textarea.value.trim(), image, subject })); location.href = 'chats.html'; });
  document.addEventListener('mousemove', (event) => document.querySelectorAll('.ai-tutor-eye').forEach((eye) => { const rect = eye.getBoundingClientRect(); const distance = Math.hypot(event.clientX - rect.left, event.clientY - rect.top) || 1; eye.querySelector('span').style.transform = `translate(${((event.clientX - rect.left) / distance) * 1.5}px, ${((event.clientY - rect.top) / distance) * 1.5}px)`; }));
})();
